
const TYPES = {
    Subscribers: Symbol.for("Subscribers"),
    Connector: Symbol.for("Connector"),
    IndexRouter: Symbol.for("IndexRouter"),
    AuthRouter: Symbol.for("AuthRouter"),
    AuthController: Symbol.for("AuthController"),
    UserRouter: Symbol.for("UserRouter"),
    UserController: Symbol.for("UserController"),
    UserService: Symbol.for("UserService"),
    UserRepository: Symbol.for("UserRepository"),
    ProfileRouter: Symbol.for("ProfileRouter"),
    ProfileController: Symbol.for("ProfileController"),
    ProfileService: Symbol.for("ProfileService"),
    ProfileRepository: Symbol.for("ProfileRepository"),
    CommentRouter: Symbol.for("CommentRouter"),
    CommentController: Symbol.for("CommentController"),
    CommentService: Symbol.for("CommentService"),
    CommentRepository: Symbol.for("CommentRepository"),
    LikeRouter: Symbol.for("LikeRouter"),
    LikeController: Symbol.for("LikeController"),
    LikeService: Symbol.for("LikeService"),
    LikeRepository: Symbol.for("LikeRepository"),
    CategoryRouter: Symbol.for("CategoryRouter"),
    CategoryController: Symbol.for("CategoryController"),
    CategoryService: Symbol.for("CategoryService"),
    CategoryRepository: Symbol.for("CategoryRepository"),
    EmailService: Symbol.for("EmailService"),
    TokenRouter: Symbol.for("TokenRouter"),
    TokenController: Symbol.for("TokenController"),
    TokenService: Symbol.for("TokenService"),
    TokenRepository: Symbol.for("TokenRepository"),

    ProvinceRouter: Symbol.for("ProvinceRouter"),
    ProvinceController: Symbol.for("ProvinceController"),
    ProvinceService: Symbol.for("ProvinceService"),
    ProvinceRepository: Symbol.for("ProvinceRepository"),

    CityRouter: Symbol.for("CityRouter"),
    CityController: Symbol.for("CityController"),
    CityService: Symbol.for("CityService"),
    CityRepository: Symbol.for("CityRepository"),
    ProducerDispatcher: Symbol.for("ProducerDispatcher"),
    ConsumerDispatcher: Symbol.for("ConsumerDispatcher")
};

export { TYPES };